// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/embedding.proto

package embedding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Embedding           `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetVectors() []*Embedding {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_proto_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type RerankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Documents     []string               `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_proto_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type RerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RerankResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_proto_embedding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{4}
}

func (x *RerankResponse) GetResults() []*RerankResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RerankResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResult) Reset() {
	*x = RerankResult{}
	mi := &file_proto_embedding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResult) ProtoMessage() {}

func (x *RerankResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResult.ProtoReflect.Descriptor instead.
func (*RerankResult) Descriptor() ([]byte, []int) {
	return file_proto_embedding_proto_rawDescGZIP(), []int{5}
}

func (x *RerankResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RerankResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_embedding_proto protoreflect.FileDescriptor

const file_proto_embedding_proto_rawDesc = "" +
	"\n" +
	"\x15proto/embedding.proto\x12\tembedding\"$\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"?\n" +
	"\rEmbedResponse\x12.\n" +
	"\avectors\x18\x01 \x03(\v2\x14.embedding.EmbeddingR\avectors\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"X\n" +
	"\rRerankRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tdocuments\x18\x02 \x03(\tR\tdocuments\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"C\n" +
	"\x0eRerankResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.embedding.RerankResultR\aresults\":\n" +
	"\fRerankResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score2\x8d\x01\n" +
	"\x10EmbeddingService\x12:\n" +
	"\x05Embed\x12\x17.embedding.EmbedRequest\x1a\x18.embedding.EmbedResponse\x12=\n" +
	"\x06Rerank\x12\x18.embedding.RerankRequest\x1a\x19.embedding.RerankResponseB2Z0github.com/codebase-copilot/core/proto/embeddingb\x06proto3"

var (
	file_proto_embedding_proto_rawDescOnce sync.Once
	file_proto_embedding_proto_rawDescData []byte
)

func file_proto_embedding_proto_rawDescGZIP() []byte {
	file_proto_embedding_proto_rawDescOnce.Do(func() {
		file_proto_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_embedding_proto_rawDesc), len(file_proto_embedding_proto_rawDesc)))
	})
	return file_proto_embedding_proto_rawDescData
}

var file_proto_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_embedding_proto_goTypes = []any{
	(*EmbedRequest)(nil),   // 0: embedding.EmbedRequest
	(*EmbedResponse)(nil),  // 1: embedding.EmbedResponse
	(*Embedding)(nil),      // 2: embedding.Embedding
	(*RerankRequest)(nil),  // 3: embedding.RerankRequest
	(*RerankResponse)(nil), // 4: embedding.RerankResponse
	(*RerankResult)(nil),   // 5: embedding.RerankResult
}
var file_proto_embedding_proto_depIdxs = []int32{
	2, // 0: embedding.EmbedResponse.vectors:type_name -> embedding.Embedding
	5, // 1: embedding.RerankResponse.results:type_name -> embedding.RerankResult
	0, // 2: embedding.EmbeddingService.Embed:input_type -> embedding.EmbedRequest
	3, // 3: embedding.EmbeddingService.Rerank:input_type -> embedding.RerankRequest
	1, // 4: embedding.EmbeddingService.Embed:output_type -> embedding.EmbedResponse
	4, // 5: embedding.EmbeddingService.Rerank:output_type -> embedding.RerankResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_embedding_proto_init() }
func file_proto_embedding_proto_init() {
	if File_proto_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_embedding_proto_rawDesc), len(file_proto_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embedding_proto_goTypes,
		DependencyIndexes: file_proto_embedding_proto_depIdxs,
		MessageInfos:      file_proto_embedding_proto_msgTypes,
	}.Build()
	File_proto_embedding_proto = out.File
	file_proto_embedding_proto_goTypes = nil
	file_proto_embedding_proto_depIdxs = nil
}
